name: tezda_task
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_storage: ^12.4.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  go_router: ^15.2.4
  image_picker: ^1.1.2
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.6.1
  toastification: ^3.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
