// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFHQP6sT7iYS9LD5imVP_UHh1xUoTBQo8',
    appId: '1:842639961599:web:c7b8929fe0e7e520ef4bca',
    messagingSenderId: '842639961599',
    projectId: 'tezda-be',
    authDomain: 'tezda-be.firebaseapp.com',
    storageBucket: 'tezda-be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7slhvRBInJ7yVzhPJNHp_zYb8OZT90NI',
    appId: '1:842639961599:android:3aed120b86263c1aef4bca',
    messagingSenderId: '842639961599',
    projectId: 'tezda-be',
    storageBucket: 'tezda-be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnBXuUWQW0q2ORV9Ms5akAKA7DNC01BjU',
    appId: '1:842639961599:ios:1b7c22854c53e243ef4bca',
    messagingSenderId: '842639961599',
    projectId: 'tezda-be',
    storageBucket: 'tezda-be.firebasestorage.app',
    iosBundleId: 'com.example.tezdaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnBXuUWQW0q2ORV9Ms5akAKA7DNC01BjU',
    appId: '1:842639961599:ios:1b7c22854c53e243ef4bca',
    messagingSenderId: '842639961599',
    projectId: 'tezda-be',
    storageBucket: 'tezda-be.firebasestorage.app',
    iosBundleId: 'com.example.tezdaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFHQP6sT7iYS9LD5imVP_UHh1xUoTBQo8',
    appId: '1:842639961599:web:db40d4e69affa2f8ef4bca',
    messagingSenderId: '842639961599',
    projectId: 'tezda-be',
    authDomain: 'tezda-be.firebaseapp.com',
    storageBucket: 'tezda-be.firebasestorage.app',
  );
}
